language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage test:
      script: python3 Images/manage.py test
      script: python3 Audio/manage.py test
      script: Messages/manage.py test