language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python3 Images/manage.py test Images
  - python3 Audio/manage.py test Audio
  - python3 Messages/manage.py test Messages