# Generated by Django 2.2.4 on 2019-09-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('from_user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('text', models.CharField(max_length=2048, null=True)),
                ('image_uuid', models.UUIDField(null=True)),
                ('audio_uuid', models.UUIDField(null=True)),
            ],
        ),
    ]
