# Generated by Django 2.2.4 on 2019-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessagesApp', '0003_auto_20190926_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
