# Generated by Django 2.2.6 on 2019-12-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessagesApp', '0004_auto_20190930_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=2048),
        ),
    ]
